### ISSUE TITLE
Would you send pull request to renpy?

### ISSUE THREAD

**Issue by kyouryuukunn** [yukinogatari/Ren-Py-FancyText#6]
Letter-by-letter text fade was requested sometimes in renpy.
Would you send pull request to renpy?
https://github.com/renpy/renpy/issues/52
https://github.com/renpy/renpy/issues/3669

**Comment by yukinogatari** [comment]
Hey! I've thought about it before, but the implementation here is really hacky and probably not fit to go into the engine as is. I of course have no issue with someone taking my code and reworking it for proper engine integration, but I wouldn't be able to do it myself until the next time I work on a Ren'Py title, and I can't say for sure when that will be.

**Comment by kyouryuukunn** [comment]
Thank you.

**Comment by kyouryuukunn** [comment]
I changed some codes and send pull request.
https://github.com/renpy/renpy/pull/5329

**Comment by renpytom** [comment]
While I don't love the transform-per-character approach used here, I'm looking at the possibility of feeding additional information into a shader used for text rendering that these effects will be possible.

**Comment by yukinogatari** [comment]
That would be great! I recognize that the approach used here is far from ideal, but I needed something quick and didn't have time to put together a nicer implementation. It's been a while since I've poked at this code, but I think as long as the shader has access to the current time and the time each glyph is expected to appear, you can do just about anything you'd want.
